package Shapes.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Color;
import java.awt.Dimension;

public class MyCanvas extends JFrame {
  private JPanel panel = new JPanel() {
    @Override
    protected void paintComponent(Graphics graphics) {
      super.paintComponent(graphics);
      graphics.setColor(Color.black);
      graphics.drawOval(0, 0, 6, 6);
      graphics.setColor(Color.blue);
      graphics.drawRect(30, 30, 4, 4);
      {
        int[] xPoints = {-10, -13, -7};
        int[] yPoints = {-10, -4, -4};

        graphics.fillPolygon(xPoints, yPoints, 3);
      }
    }
  };
  public void initialize() {
    this.setTitle("MyCanvas");
    this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.add(panel);
    panel.setPreferredSize(new Dimension(500, 500));
    this.pack();
    this.setVisible(true);
  }

  public static void main(String[] args) {
    MyCanvas canvas = new MyCanvas();
    canvas.initialize();
  }
}
