package Shapes.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Color;
import java.awt.Dimension;

public class MyCanvas extends JFrame {
  private JPanel panel = new JPanel() {
    @Override
    protected void paintComponent(Graphics graphics) {
      super.paintComponent(graphics);
      graphics.setColor(Color.green);
      graphics.drawOval(10, 10, 80, 80);
      graphics.setColor(Color.blue);
      graphics.drawRect(70, 30, 100, 100);
      {
        graphics.setColor(Color.red);
        int[] xPoints = {50, 20, 80};
        int[] yPoints = {50, 110, 110};

        graphics.fillPolygon(xPoints, yPoints, 3);
      }
    }
  };
  public void initialize() {
    this.setTitle("MyCanvas");
    this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.add(panel);
    panel.setPreferredSize(new Dimension(500, 500));
    this.pack();
    this.setVisible(true);
  }

  public static void main(String[] args) {
    MyCanvas canvas = new MyCanvas();
    canvas.initialize();
  }
}
