package Shapes.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCanvas = createDescriptorForCanvas();
  /*package*/ final ConceptDescriptor myConceptCircle = createDescriptorForCircle();
  /*package*/ final ConceptDescriptor myConceptColor = createDescriptorForColor();
  /*package*/ final ConceptDescriptor myConceptColorReference = createDescriptorForColorReference();
  /*package*/ final ConceptDescriptor myConceptShape = createDescriptorForShape();
  /*package*/ final ConceptDescriptor myConceptSquare = createDescriptorForSquare();
  /*package*/ final ConceptDescriptor myConceptTriangle = createDescriptorForTriangle();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, "jetbrains.mps.execution.util");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCanvas, myConceptCircle, myConceptColor, myConceptColorReference, myConceptShape, myConceptSquare, myConceptTriangle);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Canvas:
        return myConceptCanvas;
      case LanguageConceptSwitch.Circle:
        return myConceptCircle;
      case LanguageConceptSwitch.Color:
        return myConceptColor;
      case LanguageConceptSwitch.ColorReference:
        return myConceptColorReference;
      case LanguageConceptSwitch.Shape:
        return myConceptShape;
      case LanguageConceptSwitch.Square:
        return myConceptSquare;
      case LanguageConceptSwitch.Triangle:
        return myConceptTriangle;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCanvas() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Canvas", 0x959e7cc905384a6fL, 0xb1c68b569680b56cL, 0x6afdf4578e7e69eeL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:291bebe9-be25-4a24-b398-6267411dd1e4(Shapes.structure)/7709586794018138606");
    b.version(3);
    b.aggregate("shapes", 0x6afdf4578e7e69f5L).target(0x959e7cc905384a6fL, 0xb1c68b569680b56cL, 0x6afdf4578e7e69dcL).optional(true).ordered(true).multiple(true).origin("7709586794018138613").done();
    b.alias("canvas");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCircle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Circle", 0x959e7cc905384a6fL, 0xb1c68b569680b56cL, 0x6afdf4578e7e69e0L);
    b.class_(false, false, false);
    // extends: Shapes.structure.Shape
    b.super_(0x959e7cc905384a6fL, 0xb1c68b569680b56cL, 0x6afdf4578e7e69dcL);
    b.origin("r:291bebe9-be25-4a24-b398-6267411dd1e4(Shapes.structure)/7709586794018138592");
    b.version(3);
    b.property("xPosition", 0x6afdf4578e7e69e2L).type(PrimitiveTypeId.INTEGER).origin("7709586794018138594").done();
    b.property("yPosition", 0x6afdf4578e7e69e3L).type(PrimitiveTypeId.INTEGER).origin("7709586794018138595").done();
    b.property("radius", 0x6afdf4578e7e69e4L).type(PrimitiveTypeId.INTEGER).origin("7709586794018138596").done();
    b.alias("circle");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Color", 0x959e7cc905384a6fL, 0xb1c68b569680b56cL, 0x6f9cde3466746208L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:291bebe9-be25-4a24-b398-6267411dd1e4(Shapes.structure)/8042547351215432200");
    b.version(3);
    b.alias("color");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColorReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "ColorReference", 0x959e7cc905384a6fL, 0xb1c68b569680b56cL, 0x6f9cde3466788832L);
    b.class_(false, false, false);
    b.origin("r:291bebe9-be25-4a24-b398-6267411dd1e4(Shapes.structure)/8042547351215704114");
    b.version(3);
    b.associate("target", 0x6f9cde3466788833L).target(0x959e7cc905384a6fL, 0xb1c68b569680b56cL, 0x6f9cde3466746208L).optional(false).origin("8042547351215704115").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShape() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Shape", 0x959e7cc905384a6fL, 0xb1c68b569680b56cL, 0x6afdf4578e7e69dcL);
    b.class_(false, true, false);
    b.origin("r:291bebe9-be25-4a24-b398-6267411dd1e4(Shapes.structure)/7709586794018138588");
    b.version(3);
    b.aggregate("color", 0x6f9cde3466788840L).target(0x959e7cc905384a6fL, 0xb1c68b569680b56cL, 0x6f9cde3466788832L).optional(true).ordered(true).multiple(false).origin("8042547351215704128").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSquare() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Square", 0x959e7cc905384a6fL, 0xb1c68b569680b56cL, 0x6afdf4578e7e69e7L);
    b.class_(false, false, false);
    // extends: Shapes.structure.Shape
    b.super_(0x959e7cc905384a6fL, 0xb1c68b569680b56cL, 0x6afdf4578e7e69dcL);
    b.origin("r:291bebe9-be25-4a24-b398-6267411dd1e4(Shapes.structure)/7709586794018138599");
    b.version(3);
    b.property("xPosition", 0x6afdf4578e7e69e8L).type(PrimitiveTypeId.INTEGER).origin("7709586794018138600").done();
    b.property("yPosition", 0x6afdf4578e7e69ebL).type(PrimitiveTypeId.INTEGER).origin("7709586794018138603").done();
    b.property("size", 0x6afdf4578e7e69ecL).type(PrimitiveTypeId.INTEGER).origin("7709586794018138604").done();
    b.alias("square");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTriangle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Triangle", 0x959e7cc905384a6fL, 0xb1c68b569680b56cL, 0x6afdf4578e7f3bacL);
    b.class_(false, false, false);
    // extends: Shapes.structure.Shape
    b.super_(0x959e7cc905384a6fL, 0xb1c68b569680b56cL, 0x6afdf4578e7e69dcL);
    b.origin("r:291bebe9-be25-4a24-b398-6267411dd1e4(Shapes.structure)/7709586794018192300");
    b.version(3);
    b.property("xPosition", 0x6afdf4578e7f3baeL).type(PrimitiveTypeId.INTEGER).origin("7709586794018192302").done();
    b.property("yPosition", 0x6afdf4578e7f3bafL).type(PrimitiveTypeId.INTEGER).origin("7709586794018192303").done();
    b.property("base", 0x6afdf4578e7f3bb0L).type(PrimitiveTypeId.INTEGER).origin("7709586794018192304").done();
    b.property("height", 0x6afdf4578e7f3bb1L).type(PrimitiveTypeId.INTEGER).origin("7709586794018192305").done();
    b.alias("triangle");
    return b.create();
  }
}
